
const shopsFile = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        label: "商家编码",
        prop: "merchantCode",
        width: 200,
        type: 'none',
        isShow: false,
        isFixed: false
      }, {
        label: "商家名称",
        prop: "merchantName",
        width: 180,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "商家简称",
        prop: "merchantShortName",
        width: 100,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "商家绑定仓库",
        prop: "warehouseName",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "所属销司计费规则",
        prop: "belongCompanyCostRule",
        width: 150,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '格匠',
          value: 'GE_JIANG'
        }, {
          label: '广州销售公司',
          value: 'GUANG_ZHOU'
        }, {
          label: '佛山销售公司',
          value: 'FO_SHAN'
        }, {
          label: '其他销售公司',
          value: 'OTHER'
        }]
      }, {
        label: "机构代码",
        prop: "institutionCode",
        width: 150,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "商家类型",
        prop: "belongCompanyType",
        width: 150,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '格匠',
          value: 'GE_JIANG'
        }, {
          label: '广州销售公司',
          value: 'GUANG_ZHOU'
        }, {
          label: '佛山销售公司',
          value: 'FO_SHAN'
        }, {
          label: '其他销售公司',
          value: 'OTHER'
        }]
      }, {
        label: "商家属性",
        prop: "merchantType",
        width: 150,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '前置仓商家',
          value: 'PRE'
        }, {
          label: '大仓商家',
          value: 'BIG'
        }, {
          label: '销售公司',
          value: 'SALES'
        }, {
          label: '其他商家',
          value: 'OTHER'
        }]
      }, {
        label: "所属销售公司",
        prop: "belongSalesCompanyName",
        width: 160,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "商家联系电话",
        prop: "linkmanPhone",
        width: 130,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "商家联系人",
        prop: "merchantLinkman",
        width: 100,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "手机号",
        prop: "merchantPhone",
        width: 130,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "接收工程单短信通知",
        prop: "isSendToBSms",
        width: 180,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "接收用户单短信通知",
        prop: "isSendToCSms",
        width: 180,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "电子邮箱",
        prop: "email",
        width: 180,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "门店地址",
        prop: "storeAddress",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "收货人",
        prop: "receiptPerson",
        width: 100,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "收货电话",
        prop: "receiptPhone",
        width: 130,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "收货地址",
        prop: "receiptAddress",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "省",
        prop: "province",
        width: 100,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "市",
        prop: "city",
        width: 100,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "区",
        prop: "region",
        width: 100,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "街道",
        prop: "street",
        width: 100,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "备注",
        prop: "comment",
        width: 100,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        label: "商家编码",
        prop: "merchantCode",
        width: 200,
        type: 'none',
        isShow: false,
        isFixed: false
      }, {
        label: "商家名称",
        prop: "merchantName",
        width: 180,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "商家简称",
        prop: "merchantShortName",
        width: 100,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "商家绑定仓库",
        prop: "warehouseName",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "所属销司计费规则",
        prop: "belongCompanyCostRule",
        width: 150,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '格匠',
          value: 'GE_JIANG'
        }, {
          label: '广州销售公司',
          value: 'GUANG_ZHOU'
        }, {
          label: '佛山销售公司',
          value: 'FO_SHAN'
        }, {
          label: '其他销售公司',
          value: 'OTHER'
        }]
      }, {
        label: "机构代码",
        prop: "institutionCode",
        width: 150,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "商家类型",
        prop: "belongCompanyType",
        width: 150,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '格匠',
          value: 'GE_JIANG'
        }, {
          label: '广州销售公司',
          value: 'GUANG_ZHOU'
        }, {
          label: '佛山销售公司',
          value: 'FO_SHAN'
        }, {
          label: '其他销售公司',
          value: 'OTHER'
        }]
      }, {
        label: "商家属性",
        prop: "merchantType",
        width: 150,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '前置仓商家',
          value: 'PRE'
        }, {
          label: '大仓商家',
          value: 'BIG'
        }, {
          label: '销售公司',
          value: 'SALES'
        }, {
          label: '其他商家',
          value: 'OTHER'
        }]
      }, {
        label: "所属销售公司",
        prop: "belongSalesCompanyName",
        width: 160,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "商家联系电话",
        prop: "linkmanPhone",
        width: 130,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "商家联系人",
        prop: "merchantLinkman",
        width: 100,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "手机号",
        prop: "merchantPhone",
        width: 130,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "接收工程单短信通知",
        prop: "isSendToBSms",
        width: 180,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "接收用户单短信通知",
        prop: "isSendToCSms",
        width: 180,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "电子邮箱",
        prop: "email",
        width: 180,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "门店地址",
        prop: "storeAddress",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "收货人",
        prop: "receiptPerson",
        width: 100,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "收货电话",
        prop: "receiptPhone",
        width: 130,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "收货地址",
        prop: "receiptAddress",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "省",
        prop: "province",
        width: 100,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "市",
        prop: "city",
        width: 100,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "区",
        prop: "region",
        width: 100,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "街道",
        prop: "street",
        width: 100,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "备注",
        prop: "comment",
        width: 100,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default shopsFile
