
const original = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "所属仓库",
        dataKey: "warehouseName",
        key: "warehouseName",
        width: 200,
        type: 'dialog',
        isShow: true,
        isFixed: false
      }, {
        title: "物料代码 / 套机码",
        dataKey: "materialCode",
        key: "materialCode",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品类型",
        dataKey: "materialType",
        key: "materialType",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "物料名称",
        dataKey: "materialName",
        key: "materialName",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "物料型号",
        dataKey: "materialSpecification",
        key: "materialSpecification",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "现有量",
        dataKey: "nowNumber",
        key: "nowNumber",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "冻结量",
        dataKey: "frozenNumber",
        key: "frozenNumber",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "安全库存",
        dataKey: "safeNumber",
        key: "safeNumber",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "库存上限",
        dataKey: "excessNumber",
        key: "excessNumber",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "所属仓库",
        dataKey: "warehouseName",
        key: "warehouseName",
        width: 200,
        type: 'dialog',
        isShow: true,
        isFixed: false
      }, {
        title: "物料代码 / 套机码",
        dataKey: "materialCode",
        key: "materialCode",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "产品类型",
        dataKey: "materialType",
        key: "materialType",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "物料名称",
        dataKey: "materialName",
        key: "materialName",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "物料型号",
        dataKey: "materialSpecification",
        key: "materialSpecification",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "现有量",
        dataKey: "nowNumber",
        key: "nowNumber",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "冻结量",
        dataKey: "frozenNumber",
        key: "frozenNumber",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "安全库存",
        dataKey: "safeNumber",
        key: "safeNumber",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "库存上限",
        dataKey: "excessNumber",
        key: "excessNumber",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default original
