
const checkMission = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: "processStatus",
        width: 200,
        type: 'select',
        options: [{
          label: '制单',
          value: 'INVENTORY_TASK_CREATE'
        }, {
          label: '盘点中',
          value: 'INVENTORY_TASK_START'
        }, {
          label: '审核',
          value: 'INVENTORY_TASK_AUDIT'
        }, {
          label: '归档',
          value: 'INVENTORY_TASK_DOC'
        }],
        isShow: true,
        isFixed: false
      }, {
        title: "盘点任务单号",
        dataKey: "inventoryTaskOrderCode",
        key: "inventoryTaskOrderCode",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点任务名称",
        dataKey: "inventoryTaskName",
        key: "inventoryTaskName",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点任务日期",
        dataKey: "inventoryTaskDate",
        key: "inventoryTaskDate",
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点类型",
        dataKey: "inventoryType",
        key: "inventoryType",
        width: 200,
        type: 'select',
        options: [{
          label: '按仓位盘点',
          value: 'CW'
        }, {
          label: '按物料盘点',
          value: 'WL'
        }],
        isShow: true,
        isFixed: false
      }, {
        title: "盘点方式",
        dataKey: "isOpenCheck",
        key: "isOpenCheck",
        width: 200,
        type: 'select',
        options: [{
          label: '明盘',
          value: 1
        }, {
          label: '暗盘',
          value: 2
        }],
        isShow: true,
        isFixed: false
      }, {
        title: "盈亏总数量",
        dataKey: "profitAndLossQuantitySum",
        key: "profitAndLossQuantitySum",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "comment",
        key: "comment",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: "processStatus",
        width: 200,
        type: 'select',
        options: [{
          label: '制单',
          value: 'INVENTORY_TASK_CREATE'
        }, {
          label: '盘点中',
          value: 'INVENTORY_TASK_START'
        }, {
          label: '审核',
          value: 'INVENTORY_TASK_AUDIT'
        }, {
          label: '归档',
          value: 'INVENTORY_TASK_DOC'
        }],
        isShow: true,
        isFixed: false
      }, {
        title: "盘点任务单号",
        dataKey: "inventoryTaskOrderCode",
        key: "inventoryTaskOrderCode",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点任务名称",
        dataKey: "inventoryTaskName",
        key: "inventoryTaskName",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点任务日期",
        dataKey: "inventoryTaskDate",
        key: "inventoryTaskDate",
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点类型",
        dataKey: "inventoryType",
        key: "inventoryType",
        width: 200,
        type: 'select',
        options: [{
          label: '按仓位盘点',
          value: 'CW'
        }, {
          label: '按物料盘点',
          value: 'WL'
        }],
        isShow: true,
        isFixed: false
      }, {
        title: "盘点方式",
        dataKey: "isOpenCheck",
        key: "isOpenCheck",
        width: 200,
        type: 'select',
        options: [{
          label: '明盘',
          value: 1
        }, {
          label: '暗盘',
          value: 2
        }],
        isShow: true,
        isFixed: false
      }, {
        title: "盈亏总数量",
        dataKey: "profitAndLossQuantitySum",
        key: "profitAndLossQuantitySum",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "comment",
        key: "comment",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default checkMission
