
const allotSlip = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "流程状态",
        key: "processStatus",
        dataKey: "processStatus",
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'select',
        options: [
          {
            label: '制单',
            value: 'ALLOCATION_ORDER_CREATE'
          }, {
            label: '等待出库',
            value: 'ALLOCATION_ORDER_WF'
          }, {
            label: '正在出库',
            value: 'ALLOCATION_ORDER_OUT'
          }, {
            label: '调拨中',
            value: 'ALLOCATION_ORDER_ING'
          }, {
            label: '正在入库',
            value: 'ALLOCATION_ORDER_IN_WAREHOUSE_ING'
          }, {
            label: '归档',
            value: 'ALLOCATION_ORDER_DOC'
          }, {
            label: '反向调拨',
            value: 'ALLOCATION_ORDER_RETURN'
          }, {
            label: '调拨订单无效',
            value: 'ALLOCATION_ORDER_INVALID'
          }
        ] }, {
        title: "调拨类型",
        key: 'allocationType',
        dataKey: "allocationType",
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'select',
        options: [{
          label: '大仓至前置仓',
          value: 'BIG_TO_PRE'
        }, {
          label: '前置仓至大仓',
          value: 'PRE_TO_BIG'
        }, {
          label: '前置仓平调',
          value: 'PRE_TO_PRE'
        }, {
          label: '物流系统到中转仓',
          value: 'LOG_TO_MID'
        }]
      }, {
        title: "调拨单号",
        key: "allocationCode",
        dataKey: "allocationCode",
        width: 180,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "目的仓库名称",
        key: 'toWarehouseName',
        dataKey: "toWarehouseName",
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'dialog'
      }, {
        title: "提货仓库名称",
        dataKey: "pickWarehouseName",
        key: 'pickWarehouseName',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'dialog'
      }, {
        title: "推送至物流系统",
        dataKey: "isNeedTransport",
        key: 'isNeedTransport',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'dialog'
      }, {
        title: "收货地址",
        dataKey: "receiptAddress",
        key: 'receiptAddress',
        width: 180,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "收货人",
        dataKey: "receiptPerson",
        key: 'receiptPerson',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "收货电话",
        dataKey: "receiptPhone",
        key: 'receiptPhone',
        width: 180,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "总数量",
        dataKey: "totalNumber",
        key: 'totalNumber',
        width: 100,
        isShow: true,
        isFixed: false,
        type: 'none'
      }, {
        title: "总体积",
        dataKey: "totalVolume",
        key: 'totalVolume',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'none'
      }, {
        title: "车队名称",
        dataKey: "carrierName",
        key: 'carrierName',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      },
      {
        title: "司机姓名",
        dataKey: "driverName",
        key: 'driverName',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "司机电话",
        dataKey: "driverPhone",
        key: 'driverPhone',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "打印次数",
        dataKey: "numberOfPrints",
        key: 'numberOfPrints',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'none'
      }, {
        title: "车牌号",
        dataKey: "licensePlateNumber",
        key: 'licensePlateNumber',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'none'
      }, {
        title: "备注",
        dataKey: "comment",
        key: 'comment',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "目的仓库编码",
        dataKey: "toWarehouseCode",
        key: 'toWarehouseCode',
        width: 120,
        isShow: false,
        isFixed: false,
        type: 'text'
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "流程状态",
        key: "processStatus",
        dataKey: "processStatus",
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'select',
        options: [
          {
            label: '制单',
            value: 'ALLOCATION_ORDER_CREATE'
          }, {
            label: '等待出库',
            value: 'ALLOCATION_ORDER_WF'
          }, {
            label: '正在出库',
            value: 'ALLOCATION_ORDER_OUT'
          }, {
            label: '调拨中',
            value: 'ALLOCATION_ORDER_ING'
          }, {
            label: '正在入库',
            value: 'ALLOCATION_ORDER_IN_WAREHOUSE_ING'
          }, {
            label: '归档',
            value: 'ALLOCATION_ORDER_DOC'
          }, {
            label: '反向调拨',
            value: 'ALLOCATION_ORDER_RETURN'
          }, {
            label: '调拨订单无效',
            value: 'ALLOCATION_ORDER_INVALID'
          }
        ] }, {
        title: "调拨类型",
        key: 'allocationType',
        dataKey: "allocationType",
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'select',
        options: [{
          label: '大仓至前置仓',
          value: 'BIG_TO_PRE'
        }, {
          label: '前置仓至大仓',
          value: 'PRE_TO_BIG'
        }, {
          label: '前置仓平调',
          value: 'PRE_TO_PRE'
        }, {
          label: '物流系统到中转仓',
          value: 'LOG_TO_MID'
        }]
      }, {
        title: "调拨单号",
        key: "allocationCode",
        dataKey: "allocationCode",
        width: 180,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "目的仓库名称",
        key: 'toWarehouseName',
        dataKey: "toWarehouseName",
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'dialog'
      }, {
        title: "提货仓库名称",
        dataKey: "pickWarehouseName",
        key: 'pickWarehouseName',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'dialog'
      }, {
        title: "推送至物流系统",
        dataKey: "isNeedTransport",
        key: 'isNeedTransport',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'dialog'
      }, {
        title: "收货地址",
        dataKey: "receiptAddress",
        key: 'receiptAddress',
        width: 180,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "收货人",
        dataKey: "receiptPerson",
        key: 'receiptPerson',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "收货电话",
        dataKey: "receiptPhone",
        key: 'receiptPhone',
        width: 180,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "总数量",
        dataKey: "totalNumber",
        key: 'totalNumber',
        width: 100,
        isShow: true,
        isFixed: false,
        type: 'none'
      }, {
        title: "总体积",
        dataKey: "totalVolume",
        key: 'totalVolume',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'none'
      }, {
        title: "车队名称",
        dataKey: "carrierName",
        key: 'carrierName',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      },
      {
        title: "司机姓名",
        dataKey: "driverName",
        key: 'driverName',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "司机电话",
        dataKey: "driverPhone",
        key: 'driverPhone',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "打印次数",
        dataKey: "numberOfPrints",
        key: 'numberOfPrints',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'none'
      }, {
        title: "车牌号",
        dataKey: "licensePlateNumber",
        key: 'licensePlateNumber',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'none'
      }, {
        title: "备注",
        dataKey: "comment",
        key: 'comment',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "目的仓库编码",
        dataKey: "toWarehouseCode",
        key: 'toWarehouseCode',
        width: 120,
        isShow: false,
        isFixed: false,
        type: 'text'
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default allotSlip
