
const inputSlip = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        width: 180,
        type: 'multiple',
        options: [{
          label: '制单',
          value: 'IN_WAREHOUSE_ORDER_CREATE'
        }, {
          label: '入库中',
          value: 'IN_WAREHOUSE_ORDER_ING'
        }, {
          label: '归档',
          value: 'IN_WAREHOUSE_ORDER_DOC'
        }],
        isShow: true,
        isFixed: false,
        title: "流程状态",
        align: 'left',
        key: `processStatus`,
        dataKey: `processStatus`
      }, {
        width: 150,
        type: 'select',
        options: [{
          label: '调拨入库',
          value: 'ALLOCATION'
        }, {
          label: '销售订单退货',
          value: 'SALE_RETURN'
        }],
        isShow: true,
        isFixed: false,
        title: "入库类型",
        align: 'left',
        key: `type`,
        dataKey: `type`
      }, {
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false,
        title: "入库单号",
        align: 'left',
        key: `inWarehouseCode`,
        dataKey: `inWarehouseCode`
      }, {
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false,
        title: "入库仓库名称",
        align: 'left',
        key: `warehouseName`,
        dataKey: `warehouseName`
      }, {
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false,
        title: "验货人",
        align: 'left',
        key: `inspectionPerson`,
        dataKey: `inspectionPerson`
      }, {
        width: 150,
        type: 'none',
        isShow: true,
        isFixed: false,
        title: "总数量",
        align: 'left',
        key: `totalNumber`,
        dataKey: `totalNumber`
      }, {
        width: 150,
        type: 'none',
        isShow: true,
        isFixed: false,
        title: "总体积",
        align: 'left',
        key: `totalVolume`,
        dataKey: `totalVolume`
      }, {
        title: "打印次数",
        dataKey: "numberOfPrints",
        key: 'numberOfPrints',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'none'
      }, {
        width: 150,
        type: 'none',
        isShow: true,
        isFixed: false,
        title: "备注",
        align: 'left',
        key: `comment`,
        dataKey: `comment`
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'daterange',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'daterange',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        width: 180,
        type: 'multiple',
        options: [{
          label: '制单',
          value: 'IN_WAREHOUSE_ORDER_CREATE'
        }, {
          label: '入库中',
          value: 'IN_WAREHOUSE_ORDER_ING'
        }, {
          label: '归档',
          value: 'IN_WAREHOUSE_ORDER_DOC'
        }],
        isShow: true,
        isFixed: false,
        title: "流程状态",
        align: 'left',
        key: `processStatus`,
        dataKey: `processStatus`
      }, {
        width: 150,
        type: 'select',
        options: [{
          label: '调拨入库',
          value: 'ALLOCATION'
        }, {
          label: '销售订单退货',
          value: 'SALE_RETURN'
        }],
        isShow: true,
        isFixed: false,
        title: "入库类型",
        align: 'left',
        key: `type`,
        dataKey: `type`
      }, {
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false,
        title: "入库单号",
        align: 'left',
        key: `inWarehouseCode`,
        dataKey: `inWarehouseCode`
      }, {
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false,
        title: "入库仓库名称",
        align: 'left',
        key: `warehouseName`,
        dataKey: `warehouseName`
      }, {
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false,
        title: "验货人",
        align: 'left',
        key: `inspectionPerson`,
        dataKey: `inspectionPerson`
      }, {
        width: 150,
        type: 'none',
        isShow: true,
        isFixed: false,
        title: "总数量",
        align: 'left',
        key: `totalNumber`,
        dataKey: `totalNumber`
      }, {
        width: 150,
        type: 'none',
        isShow: true,
        isFixed: false,
        title: "总体积",
        align: 'left',
        key: `totalVolume`,
        dataKey: `totalVolume`
      }, {
        title: "打印次数",
        dataKey: "numberOfPrints",
        key: 'numberOfPrints',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'none'
      }, {
        width: 150,
        type: 'none',
        isShow: true,
        isFixed: false,
        title: "备注",
        align: 'left',
        key: `comment`,
        dataKey: `comment`
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'daterange',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'daterange',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default inputSlip
