
const adjustSlip = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "库位调整单号",
        dataKey: "positionResetCode",
        key: 'positionResetCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "条码",
        dataKey: "barCode",
        key: 'barCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "物料代码",
        dataKey: "materialCode",
        key: 'materialCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "物料名称",
        dataKey: "materialName",
        key: 'materialName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "物料型号",
        dataKey: "materialSpecification",
        key: 'materialSpecification',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "原仓库名称",
        dataKey: "orgWarehouseName",
        key: 'orgWarehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "原仓位名称",
        dataKey: "orgWarehousePositionName",
        key: 'orgWarehousePositionName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "目的仓库名称",
        dataKey: "desWarehouseName",
        key: 'desWarehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "目的仓位名称",
        dataKey: "desWarehousePositionName",
        key: 'desWarehousePositionName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "库位调整单号",
        dataKey: "positionResetCode",
        key: 'positionResetCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "条码",
        dataKey: "barCode",
        key: 'barCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "物料代码",
        dataKey: "materialCode",
        key: 'materialCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "物料名称",
        dataKey: "materialName",
        key: 'materialName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "物料型号",
        dataKey: "materialSpecification",
        key: 'materialSpecification',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "原仓库名称",
        dataKey: "orgWarehouseName",
        key: 'orgWarehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "原仓位名称",
        dataKey: "orgWarehousePositionName",
        key: 'orgWarehousePositionName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "目的仓库名称",
        dataKey: "desWarehouseName",
        key: 'desWarehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "目的仓位名称",
        dataKey: "desWarehousePositionName",
        key: 'desWarehousePositionName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default adjustSlip
