
const outputSlip = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        label: "流程状态",
        prop: "processStatus",
        width: 200,
        type: 'multiple',
        options: [{
          label: '制单',
          value: 'OUT_WAREHOUSE_ORDER_CREATE'
        }, {
          label: '等待出库',
          value: 'OUT_WAREHOUSE_ORDER_WF'
        }, {
          label: '出库中',
          value: 'OUT_WAREHOUSE_ORDER_OUT'
        }, {
          label: '归档',
          value: 'OUT_WAREHOUSE_ORDER_DOC'
        }],
        isShow: true,
        isFixed: false
      }, {
        label: "出库单号",
        prop: "outWarehouseCode",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "销售单号 / 调拨单号",
        prop: "saleOrAllCodes",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "出库类型",
        prop: "type",
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '调拨出库',
          value: 'DB'
        }, {
          label: '销售订单出库',
          value: 'XS'
        }, {
          label: '派车单出库',
          value: 'PC'
        }]
      }, {
        label: "出库仓名称",
        prop: "warehouseName",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "总数量",
        prop: "totalNumber",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "总体积",
        prop: "totalVolume",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "打印次数",
        dataKey: "numberOfPrints",
        key: 'numberOfPrints',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'none'
      }, {
        label: "备注",
        prop: "comment",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "是否推送条码",
        prop: "isPush",
        width: 200,
        type: 'none',
        isShow: false,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'daterange',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'daterange',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        label: "流程状态",
        prop: "processStatus",
        width: 200,
        type: 'multiple',
        options: [{
          label: '制单',
          value: 'OUT_WAREHOUSE_ORDER_CREATE'
        }, {
          label: '等待出库',
          value: 'OUT_WAREHOUSE_ORDER_WF'
        }, {
          label: '出库中',
          value: 'OUT_WAREHOUSE_ORDER_OUT'
        }, {
          label: '归档',
          value: 'OUT_WAREHOUSE_ORDER_DOC'
        }],
        isShow: true,
        isFixed: false
      }, {
        label: "出库单号",
        prop: "outWarehouseCode",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "销售单号 / 调拨单号",
        prop: "saleOrAllCodes",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "出库类型",
        prop: "type",
        width: 200,
        type: 'select',
        isShow: true,
        isFixed: false,
        options: [{
          label: '调拨出库',
          value: 'DB'
        }, {
          label: '销售订单出库',
          value: 'XS'
        }, {
          label: '派车单出库',
          value: 'PC'
        }]
      }, {
        label: "出库仓名称",
        prop: "warehouseName",
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        label: "总数量",
        prop: "totalNumber",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "总体积",
        prop: "totalVolume",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "打印次数",
        dataKey: "numberOfPrints",
        key: 'numberOfPrints',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'none'
      }, {
        label: "备注",
        prop: "comment",
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        label: "是否推送条码",
        prop: "isPush",
        width: 200,
        type: 'none',
        isShow: false,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'daterange',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'daterange',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default outputSlip
