
const warehouseFile = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "仓库编码",
        dataKey: "warehouseCode",
        key: 'warehouseCode',
        width: 300,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "仓库名称",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "仓库类型",
        dataKey: "warehouseType",
        key: 'warehouseType',
        width: 200,
        type: 'select',
        options: [{
          label: '商家仓',
          value: 'MERCHANT'
        }, {
          label: '中转仓',
          value: 'TRANSFER'
        }, {
          label: '前置仓',
          value: 'PRE'
        }, {
          label: '大仓',
          value: 'BIG_WAREHOUSE'
        }],
        isShow: true,
        isFixed: false
      }, {
        title: "仓库负责人",
        dataKey: "warehouseKeeper",
        key: 'warehouseKeeper',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "仓库电话",
        dataKey: "linkmanPhone",
        key: 'linkmanPhone',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "仓库地址",
        dataKey: "warehouseAddress",
        key: 'warehouseAddress',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "comment",
        key: 'comment',
        width: 300,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "仓库名称",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "仓库类型",
        dataKey: "warehouseType",
        key: 'warehouseType',
        width: 200,
        type: 'select',
        options: [{
          label: '商家仓',
          value: 'MERCHANT'
        }, {
          label: '中转仓',
          value: 'TRANSFER'
        }, {
          label: '前置仓',
          value: 'PRE'
        }, {
          label: '大仓',
          value: 'BIG_WAREHOUSE'
        }],
        isShow: true,
        isFixed: false
      }, {
        title: "仓库负责人",
        dataKey: "warehouseKeeper",
        key: 'warehouseKeeper',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "仓库电话",
        dataKey: "linkmanPhone",
        key: 'linkmanPhone',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "仓库地址",
        dataKey: "warehouseAddress",
        key: 'warehouseAddress',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "仓库编码",
        dataKey: "warehouseCode",
        key: 'warehouseCode',
        width: 300,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "备注",
        dataKey: "comment",
        key: 'comment',
        width: 300,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default warehouseFile
