
const checkCollect = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "盘点汇总单号",
        dataKey: "takeStockRecordCode",
        key: 'takeStockRecordCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 200,
        type: 'multiple',
        options: [{
          label: '未开始',
          value: 'TAKE_STOCK_NO_START'
        }, {
          label: '盘点中',
          value: 'TAKE_STOCK_ING'
        }, {
          label: '盘点结束',
          value: 'TAKE_STOCK_END'
        }],
        isShow: true,
        isFixed: false
      }, {
        title: "计划盘点日期",
        dataKey: "planStartTime",
        key: 'planStartTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点开始日期",
        dataKey: "startTime",
        key: 'startTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点仓库",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点仓位",
        dataKey: "positionsName",
        key: 'positionsName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "初始盘点总数量",
        dataKey: "totalSysNumber",
        key: 'totalSysNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "实际盘点总数量",
        dataKey: "totalRealNumber",
        key: 'totalRealNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUser",
        key: 'createUser',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUser",
        key: 'updateUser',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "盘点汇总单号",
        dataKey: "takeStockRecordCode",
        key: 'takeStockRecordCode',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 200,
        type: 'multiple',
        options: [{
          label: '未开始',
          value: 'TAKE_STOCK_NO_START'
        }, {
          label: '盘点中',
          value: 'TAKE_STOCK_ING'
        }, {
          label: '盘点结束',
          value: 'TAKE_STOCK_END'
        }],
        isShow: true,
        isFixed: false
      }, {
        title: "计划盘点日期",
        dataKey: "planStartTime",
        key: 'planStartTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点开始日期",
        dataKey: "startTime",
        key: 'startTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点仓库",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "盘点仓位",
        dataKey: "positionsName",
        key: 'positionsName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "初始盘点总数量",
        dataKey: "totalSysNumber",
        key: 'totalSysNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "实际盘点总数量",
        dataKey: "totalRealNumber",
        key: 'totalRealNumber',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUser",
        key: 'createUser',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUser",
        key: 'updateUser',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default checkCollect
