
const pickUpSlip = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 150,
        type: 'select',
        options: [{
          label: '未调拨',
          value: 'PICK_ORDER_NO_ALLOCATION'
        }, {
          label: '调拨中',
          value: 'PICK_ORDER_ALLOCATION_ING'
        }, {
          label: '已调拨',
          value: 'PICK_ORDER_HAVA_ALLOCATION'
        }, {
          label: '已入调拨计划库',
          value: 'PICK_ORDER_IN_ALLOCATION_PLAN'
        }],
        isShow: true,
        isFixed: false
      }, {
        title: "提货订单号",
        dataKey: "pickingOrderCode",
        key: 'pickingOrderCode',
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "发货单号",
        dataKey: "gejiangOrderCode",
        key: 'gejiangOrderCode',
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "发货仓库",
        dataKey: "deliverWarehouse",
        key: 'deliverWarehouse',
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "商家名称",
        dataKey: "merchantName",
        key: 'merchantName',
        width: 220,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "下单时间",
        dataKey: "orderTime",
        key: 'orderTime',
        width: 180,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "货物总数量",
        dataKey: "totalAmount",
        key: 'totalAmount',
        width: 100,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "是否成功增加虚拟库存",
        dataKey: "isAddStock",
        key: 'isAddStock',
        width: 180,
        type: 'select',
        options: [{
          label: '是',
          value: '是'
        }, {
          label: '否',
          value: '否'
        }],
        isShow: true,
        isFixed: false
      }, {
        title: "提货密钥",
        dataKey: "goodsPickingKey",
        key: 'goodsPickingKey',
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "收货客户",
        dataKey: "goodsReceiptingCustomer",
        key: 'goodsReceiptingCustomer',
        width: 130,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "联系电话",
        dataKey: "phone",
        key: 'phone',
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "收货地址",
        dataKey: "goodsReceiptingAddress",
        key: 'goodsReceiptingAddress',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "订单备注",
        dataKey: "orderNotes",
        key: 'orderNotes',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "送货备注",
        dataKey: "otherNotes",
        key: 'otherNotes',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "商家编码",
        dataKey: "merchantCode",
        key: 'merchantCode',
        width: 100,
        type: 'text',
        isShow: false,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 150,
        type: 'select',
        options: [{
          label: '未调拨',
          value: 'PICK_ORDER_NO_ALLOCATION'
        }, {
          label: '调拨中',
          value: 'PICK_ORDER_ALLOCATION_ING'
        }, {
          label: '已调拨',
          value: 'PICK_ORDER_HAVA_ALLOCATION'
        }, {
          label: '已入调拨计划库',
          value: 'PICK_ORDER_IN_ALLOCATION_PLAN'
        }],
        isShow: true,
        isFixed: false
      }, {
        title: "提货订单号",
        dataKey: "pickingOrderCode",
        key: 'pickingOrderCode',
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "发货单号",
        dataKey: "gejiangOrderCode",
        key: 'gejiangOrderCode',
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "发货仓库",
        dataKey: "deliverWarehouse",
        key: 'deliverWarehouse',
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "商家名称",
        dataKey: "merchantName",
        key: 'merchantName',
        width: 220,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "下单时间",
        dataKey: "orderTime",
        key: 'orderTime',
        width: 180,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "货物总数量",
        dataKey: "totalAmount",
        key: 'totalAmount',
        width: 100,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "是否成功增加虚拟库存",
        dataKey: "isAddStock",
        key: 'isAddStock',
        width: 180,
        type: 'select',
        options: [{
          label: '是',
          value: '是'
        }, {
          label: '否',
          value: '否'
        }],
        isShow: true,
        isFixed: false
      }, {
        title: "提货密钥",
        dataKey: "goodsPickingKey",
        key: 'goodsPickingKey',
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "收货客户",
        dataKey: "goodsReceiptingCustomer",
        key: 'goodsReceiptingCustomer',
        width: 130,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "联系电话",
        dataKey: "phone",
        key: 'phone',
        width: 150,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "收货地址",
        dataKey: "goodsReceiptingAddress",
        key: 'goodsReceiptingAddress',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "订单备注",
        dataKey: "orderNotes",
        key: 'orderNotes',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "送货备注",
        dataKey: "otherNotes",
        key: 'otherNotes',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "商家编码",
        dataKey: "merchantCode",
        key: 'merchantCode',
        width: 100,
        type: 'text',
        isShow: false,
        isFixed: false
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default pickUpSlip
