
const sale = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'select',
        options: [
          {
            label: '制单',
            value: 'SALE_ORDER_CREATE'
          }, {
            label: '留料',
            value: 'SALE_ORDER_MAT'
          }, {
            label: '出库中',
            value: 'SALE_ORDER_OUT'
          }, {
            label: '归档',
            value: 'SALE_ORDER_DOC'
          }, {
            label: '销售退货',
            value: 'SALE_ORDER_RETURN'
          }
        ]
      }, {
        title: "销售单号",
        dataKey: "saleOrderCode",
        key: 'saleOrderCode',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "商家名称",
        dataKey: "merchantName",
        key: 'merchantName',
        width: 180,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "客户名称",
        dataKey: "customerName",
        key: 'customerName',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "客户电话",
        dataKey: "customerPhone",
        key: 'customerPhone',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "送货地址",
        dataKey: "receiptAddress",
        key: 'receiptAddress',
        width: 200,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "分配网点",
        dataKey: "branchName",
        key: 'branchName',
        width: 180,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "要求配送日期",
        dataKey: "requireDeliveryDate",
        key: 'requireDeliveryDate',
        width: 200,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "发货仓库",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "留料时间",
        dataKey: "matDate",
        key: 'matDate',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'daterange'
      }, {
        title: "业务员",
        dataKey: "salesman",
        key: 'salesman',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "抛单员",
        dataKey: "orderMaker",
        key: 'orderMaker',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "打印次数",
        dataKey: "numberOfPrints",
        key: 'numberOfPrints',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'none'
      }, {
        title: "备注",
        dataKey: "comment",
        key: 'comment',
        width: 200,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        label: '服务过程描述',
        prop: 'serviceProcessDescription',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "省",
        dataKey: "province",
        key: 'province',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "市",
        dataKey: "city",
        key: 'city',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "区",
        dataKey: "area",
        key: 'area',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "街道",
        dataKey: "street",
        key: 'street',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'daterange',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'daterange',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'select',
        options: [
          {
            label: '制单',
            value: 'SALE_ORDER_CREATE'
          }, {
            label: '留料',
            value: 'SALE_ORDER_MAT'
          }, {
            label: '出库中',
            value: 'SALE_ORDER_OUT'
          }, {
            label: '归档',
            value: 'SALE_ORDER_DOC'
          }, {
            label: '销售退货',
            value: 'SALE_ORDER_RETURN'
          }
        ]
      }, {
        title: "销售单号",
        dataKey: "saleOrderCode",
        key: 'saleOrderCode',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "商家名称",
        dataKey: "merchantName",
        key: 'merchantName',
        width: 180,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "客户名称",
        dataKey: "customerName",
        key: 'customerName',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "客户电话",
        dataKey: "customerPhone",
        key: 'customerPhone',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "送货地址",
        dataKey: "receiptAddress",
        key: 'receiptAddress',
        width: 200,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "分配网点",
        dataKey: "branchName",
        key: 'branchName',
        width: 180,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "要求配送日期",
        dataKey: "requireDeliveryDate",
        key: 'requireDeliveryDate',
        width: 200,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "发货仓库",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "留料时间",
        dataKey: "matDate",
        key: 'matDate',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'daterange'
      }, {
        title: "业务员",
        dataKey: "salesman",
        key: 'salesman',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "抛单员",
        dataKey: "orderMaker",
        key: 'orderMaker',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "打印次数",
        dataKey: "numberOfPrints",
        key: 'numberOfPrints',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'none'
      }, {
        title: "备注",
        dataKey: "comment",
        key: 'comment',
        width: 200,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        label: '服务过程描述',
        prop: 'serviceProcessDescription',
        width: 200,
        type: 'none',
        isShow: true,
        isFixed: false
      }, {
        title: "省",
        dataKey: "province",
        key: 'province',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "市",
        dataKey: "city",
        key: 'city',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "区",
        dataKey: "area",
        key: 'area',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "街道",
        dataKey: "street",
        key: 'street',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'daterange',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'daterange',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default sale
