
const saleReturn = {
  namespaced: true,
  state: {
    tableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        type: 'select',
        width: 150,
        isShow: true,
        isFixed: false,
        options: [{
          label: '等待取件',
          value: 'SALE_ORDER_RETURN_PICK_UP'
        }, {
          label: '入库中',
          value: 'SALE_ORDER_RETURN_PUT'
        }, {
          label: '归档',
          value: 'SALE_ORDER_RETURN_DOC'
        }]
      }, {
        title: "销售单号",
        dataKey: "saleOrderCode",
        key: 'saleOrderCode',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "退货单号",
        dataKey: "saleOrderReturnCode",
        key: 'saleOrderReturnCode',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "取件日期",
        dataKey: "pickUpDate",
        key: 'pickUpDate',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'date'
      }, {
        title: "商家名称",
        dataKey: "merchantName",
        key: 'merchantName',
        width: 180,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "客户名称",
        dataKey: "customerName",
        key: 'customerName',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "客户电话",
        dataKey: "customerPhone",
        key: 'customerPhone',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "送货地址",
        dataKey: "receiptAddress",
        key: 'receiptAddress',
        width: 200,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "收货仓库",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "备注",
        dataKey: "comment",
        key: 'comment',
        width: 200,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "省",
        dataKey: "province",
        key: 'province',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "市",
        dataKey: "city",
        key: 'city',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "区",
        dataKey: "area",
        key: 'area',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "街道",
        dataKey: "street",
        key: 'street',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ],
    defaultTableHeader: [
      {
        title: "流程状态",
        dataKey: "processStatus",
        key: 'processStatus',
        type: 'select',
        width: 150,
        isShow: true,
        isFixed: false,
        options: [{
          label: '等待取件',
          value: 'SALE_ORDER_RETURN_PICK_UP'
        }, {
          label: '入库中',
          value: 'SALE_ORDER_RETURN_PUT'
        }, {
          label: '归档',
          value: 'SALE_ORDER_RETURN_DOC'
        }]
      }, {
        title: "销售单号",
        dataKey: "saleOrderCode",
        key: 'saleOrderCode',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "退货单号",
        dataKey: "saleOrderReturnCode",
        key: 'saleOrderReturnCode',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "取件日期",
        dataKey: "pickUpDate",
        key: 'pickUpDate',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'date'
      }, {
        title: "商家名称",
        dataKey: "merchantName",
        key: 'merchantName',
        width: 180,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "客户名称",
        dataKey: "customerName",
        key: 'customerName',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "客户电话",
        dataKey: "customerPhone",
        key: 'customerPhone',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "送货地址",
        dataKey: "receiptAddress",
        key: 'receiptAddress',
        width: 200,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "收货仓库",
        dataKey: "warehouseName",
        key: 'warehouseName',
        width: 150,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "备注",
        dataKey: "comment",
        key: 'comment',
        width: 200,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "省",
        dataKey: "province",
        key: 'province',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "市",
        dataKey: "city",
        key: 'city',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "区",
        dataKey: "area",
        key: 'area',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "街道",
        dataKey: "street",
        key: 'street',
        width: 120,
        isShow: true,
        isFixed: false,
        type: 'text'
      }, {
        title: "创建时间",
        dataKey: "createTime",
        key: 'createTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "创建人",
        dataKey: "createUserName",
        key: 'createUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }, {
        title: "更新时间",
        dataKey: "updateTime",
        key: 'updateTime',
        width: 200,
        type: 'date',
        isShow: true,
        isFixed: false
      }, {
        title: "更新人",
        dataKey: "updateUserName",
        key: 'updateUserName',
        width: 200,
        type: 'text',
        isShow: true,
        isFixed: false
      }
    ]
  },
  getters: {
  },
  mutations: {
    updateTableHeader(state, newTableHeader) {
      state.tableHeader.length = 0
      state.tableHeader.push(...newTableHeader)
    }
  },
  actions: {
  }
}
export default saleReturn
